module.exports = {
  sxo_bco: ["Femenino", "Masculino"],
  region: [
    "Tarapacá",
    "Antofagasta",
    "Atacama",
    "Coquimbo",
    "Valparaíso",
    "O'higgins",
    "El Maule",
    "El Bío Bío",
    "La Araucanía",
    "Los Lagos",
    "Aysen",
    "Magallanes y Antártica Chilena",
    "Metropolitana",
    "Los Rios",
    "Arica y Parinacota",
    "Ñuble",
  ],
  u_r: ["Urbano", "Rural"],
  m_educ: [
    "Regular",
    "Especial",
    "Proyecto de Integración",
    "No aplica",
    "No responde",
  ],
  n_educ1: [
    "Sin escolarización formal adulto",
    "No escolarizado",
    "Preescolar",
    "Cursando educación basica",
    "Cursando educación basica",
    "Cursando educación media",
    "Cursando educación superior",
    "Cursando estudios de post grado",
    "No aplica",
    "No responde",
  ],
  n_educ2: [
    "Sin escolarización formal adulto",
    "Educación preescolar incompleta",
    "Educación preescolar completa",
    "Educación basica completa",
    "Educación media incompleta",
    "Educación media completa",
    "Estudios técnicos incompletos",
    "Estudios técnicos completos",
    "Estudios universitarios incompletos",
    "Estudios universitarios completos",
    "Estudios de postgrado completos",
    "Estudios de postgrado incompletos",
    "No aplica",
    "No responde",
  ],
  ocupacion: [
    "Estudiante",
    "Profesional",
    "Técnicos y Afines",
    "Gerentes, Administradores y Directivos",
    "Empleados oficina y afines",
    "Vendedores y afines",
    "Agricultores, Ganaderos, Pescadores",
    "Conductores y afines",
    "Artesanos y Operarios",
    "Obreros y Jornaleros",
    "Dueña de casa",
    "Jubilado",
    "Otros trabajadores",
    "Adulto sin ocupación",
    "No aplica",
    "No responde",
  ],
  prevision: [
    "Sin prevision",
    "Fonasa",
    "Isapre",
    "No responde",
    "Dato perdido",
  ],
  perfil_audiometrico: [
    "Descendente",
    "Ascendente",
    "Batea o U",
    "U invertida",
    "Rincon izquierdo",
    "Plano",
    "Otro",
    "Anacusia",
    "No aplica",
    "No responde",
  ],
  had: ["Nada", "Audifono", "Implante", "No responde"],
  prog_ado: [
    "Hipoacusia en menor de 4 años/ges77",
    "Hipoacusia en prematuro extremo/ges59",
    "Fonasa/Minsal",
    "Ricarte Soto",
    "Junaeb",
    "Senadis",
    "Particular",
    "Otro",
    "Ges mayor de 65 años",
    "No aplica",
    "No responde",
  ],
  dg_audio: [
    "Normoacusia",
    "Perdida auditiva leve",
    "Perdida auditiva moderada",
    "Perdida auditiva severa",
    "Perdida auditiva profunda",
    "Anacusia",
  ],
  simple: ["Si", "No", "No responde"],
  ref_seq: [
    "rs529500747",
    "rs1286249617",
    "rs80338939",
    "rs2274084",
    "rs35887622",
    "rs72474224",
    "rs80338942",
    "rs778922005",
    "rs104894403",
    "rs2274083",
    "rs750795475",
    "rs111033294",
    "rs1268045311",
    "rs1555341783",
  ],
  pos_chr13: [
    "20189559",
    "20189555",
    "20189551",
    "20189503",
    "20189481",
    "20189473",
    "20189415",
    "20189408",
    "20189386",
    "20189241",
    "20189144",
    "20188965",
    "20188950",
    "20188914",
  ],
};
